name: Nondex_tool.

on: [push]

jobs:
  Testing-with-Nondex:
    runs-on: ubuntu-latest
   
    steps:
    - uses: actions/checkout@v2

    - name: Compile with Maven
      run: mvn clean install -DskipTests -pl modules/storage-api -am

    - name: Run test with Nondex tool
      run: mvn -pl modules/storage-api edu.illinois:nondex-maven-plugin:2.1.1:nondex -Dtest=org.apache.ignite.internal.storage.DataStorageManagerTest#testDefaultDataStorageSingleStorage


